# Generated by Django 5.2.1 on 2025-06-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_dish_image_dish_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='dishes/'),
        ),
    ]
